import { AgentExecutor, AgentConfig, TaskContext, AgentResult, createAgentConfig } from './AgentExecutor.js';

const WRITER_SYSTEM_PROMPT = `You are a Writer agent in the Mosaic Protocol marketplace. Your specialty is creating clear, professional content.

## Your Capabilities:
- Report writing and documentation
- Content synthesis and organization
- Professional formatting and structure
- Executive summaries
- Technical writing

## Guidelines:
1. Write in a clear, professional tone
2. Use proper structure with headings and sections
3. Include an executive summary for longer pieces
4. Highlight key takeaways
5. Maintain consistency in formatting

## Output Structure for Reports:
# [Report Title]

## Executive Summary
[2-3 paragraph overview]

## Key Findings
- [Bullet points of main insights]

## [Main Sections as needed]
[Detailed content]

## Conclusion
[Summary and next steps if applicable]

---
*Report generated by Mosaic Protocol*

Remember: You're a paid professional writer. Deliver publication-ready content.`;

export class WriterAgent extends AgentExecutor {
    constructor(
        tokenId: number,
        name: string,
        walletPrivateKey: string,
        owner: string,
        price: bigint,
        endpoint: string = 'llama-3.3-70b-versatile'
    ) {
        const agentConfig = createAgentConfig(
            tokenId,
            name,
            'writing',
            walletPrivateKey,
            owner,
            price,
            endpoint,
            WRITER_SYSTEM_PROMPT,
            ['content_creation', 'formatting'],
            false, // Cannot hire other agents
            0
        );
        super(agentConfig);
    }

    /**
     * Write a report based on provided content
     */
    async writeReport(
        task: string,
        context: TaskContext,
        sourceContent: Map<string, string>
    ): Promise<AgentResult> {
        // Build writing prompt with all source content
        let sourcesSection = '';
        if (sourceContent.size > 0) {
            sourcesSection = '\n## Source Content to Include:\n';
            sourceContent.forEach((content, source) => {
                sourcesSection += `\n### From ${source}:\n${content}\n`;
            });
        }

        const writingPrompt = `
# Writing Task:
${task}

${sourcesSection}

# Instructions:
Create a well-structured, professional document that synthesizes all the provided information.
The output should be publication-ready.

Original request: ${context.originalTask}
`;

        return this.execute(writingPrompt, context);
    }
}

/**
 * Create Writer agent from configuration
 */
export function createWriterAgent(
    tokenId: number,
    name: string,
    walletPrivateKey: string,
    owner: string,
    price: bigint,
    endpoint: string = 'llama-3.3-70b-versatile'
): WriterAgent {
    return new WriterAgent(tokenId, name, walletPrivateKey, owner, price, endpoint);
}

/**
 * Summarizer is a specialized writer
 */
const SUMMARIZER_SYSTEM_PROMPT = `You are a Summarization agent in the Mosaic Protocol marketplace. Your specialty is condensing information into clear, concise summaries.

## Your Capabilities:
- Executive summary creation
- Key point extraction
- TL;DR generation
- Bullet point synthesis

## Guidelines:
1. Identify the most important information
2. Be concise but comprehensive
3. Use bullet points for clarity
4. Highlight actionable items
5. Keep summaries under 500 words unless specified

Remember: Brevity is key. Extract the essence.`;

export class SummarizerAgent extends AgentExecutor {
    constructor(
        tokenId: number,
        name: string,
        walletPrivateKey: string,
        owner: string,
        price: bigint,
        endpoint: string = 'llama-3.1-8b-instant'
    ) {
        const agentConfig = createAgentConfig(
            tokenId,
            name,
            'summarization',
            walletPrivateKey,
            owner,
            price,
            endpoint,
            SUMMARIZER_SYSTEM_PROMPT,
            ['summarization'],
            false,
            0
        );
        super(agentConfig);
    }
}

export function createSummarizerAgent(
    tokenId: number,
    name: string,
    walletPrivateKey: string,
    owner: string,
    price: bigint,
    endpoint: string = 'llama-3.1-8b-instant'
): SummarizerAgent {
    return new SummarizerAgent(tokenId, name, walletPrivateKey, owner, price, endpoint);
}


