import Anthropic from '@anthropic-ai/sdk';
import { config } from './config.js';

let client: Anthropic | null = null;

function getClient(): Anthropic | null {
    if (!config.anthropicApiKey || config.anthropicApiKey === 'sk-ant-...') {
        return null;
    }

    if (!client) {
        client = new Anthropic({
            apiKey: config.anthropicApiKey,
        });
    }

    return client;
}

export async function callClaude(capability: string, input: string): Promise<string> {
    const anthropic = getClient();

    if (!anthropic) {
        console.log(`   📝 Claude not configured, using cached response for ${capability}`);
        return getCachedResponse(capability);
    }

    const systemPrompts: Record<string, string> = {
        orchestration: `You are a Coordinator agent that breaks down complex tasks into subtasks. 
            Analyze the user's request and identify what specialized agents are needed.
            Be concise and list the subtasks clearly.`,
        
        research: `You are a Research agent specialized in gathering information.
            Find and compile relevant data on the given topic.
            Provide factual, well-structured research findings.`,
        
        analysis: `You are an Analyst agent specialized in analyzing data.
            Take the research data and extract key insights, patterns, and conclusions.
            Be analytical and data-driven in your response.`,
        
        writing: `You are a Writer agent specialized in creating polished content.
            Take the analysis and create a well-formatted, professional report.
            Use clear headings, bullet points, and a logical structure.`,
    };

    try {
        const response = await anthropic.messages.create({
            model: 'claude-3-haiku-20240307',
            max_tokens: 1024,
            system: systemPrompts[capability] || 'You are a helpful AI assistant.',
            messages: [
                { role: 'user', content: input }
            ],
        });

        const textContent = response.content.find(c => c.type === 'text');
        return textContent?.text || 'No response generated';
    } catch (error) {
        console.error(`Claude API error for ${capability}:`, error);
        return getCachedResponse(capability);
    }
}

function getCachedResponse(capability: string): string {
    const cached: Record<string, string> = {
        orchestration: `Task Analysis Complete:
1. Research Phase: Gather data on top Solana DeFi protocols
2. Analysis Phase: Analyze TVL, trading volume, and market trends
3. Writing Phase: Compile findings into comprehensive report`,

        research: `## Top 3 Solana DeFi Protocols Research

### 1. Jupiter (JUP)
- **TVL**: $2.1 billion
- **Type**: DEX Aggregator
- **Key Feature**: Best price execution across all Solana DEXs
- **24h Volume**: $890M

### 2. Raydium (RAY)
- **TVL**: $1.8 billion
- **Type**: AMM & Liquidity Provider
- **Key Feature**: Concentrated liquidity pools
- **24h Volume**: $650M

### 3. Marinade Finance (MNDE)
- **TVL**: $1.4 billion
- **Type**: Liquid Staking
- **Key Feature**: mSOL liquid staking token
- **Staked SOL**: 8.2M SOL`,

        analysis: `### Key Insights from Solana DeFi Analysis

**Market Position:**
- Jupiter dominates DEX aggregation with 45% market share
- Combined TVL of top 3 protocols: $5.3 billion
- Strong growth trajectory despite market volatility

**Risk Assessment:**
- Smart contract risks remain primary concern
- Liquidity fragmentation improving via aggregators
- Regulatory uncertainty in staking products

**Opportunities:**
- Cross-chain bridges expanding Solana DeFi reach
- Institutional adoption increasing
- New yield strategies emerging in liquid staking`,

        writing: `# Solana DeFi Landscape Report

## Executive Summary
The Solana DeFi ecosystem has matured significantly, with the top three protocols commanding over $5.3 billion in total value locked. This report analyzes Jupiter, Raydium, and Marinade Finance.

## Key Findings

### Market Leaders
1. **Jupiter** leads as the premier DEX aggregator, processing $890M daily
2. **Raydium** provides essential liquidity infrastructure
3. **Marinade Finance** dominates liquid staking with 8.2M SOL staked

### Investment Considerations
- Strong fundamentals across all three protocols
- Active development and community engagement
- Growing institutional interest

## Conclusion
Solana DeFi presents compelling opportunities for users seeking high-performance, low-cost DeFi interactions. The ecosystem continues to mature with robust infrastructure and innovative products.

---
*Report generated by Mosaic Protocol AI Agents*`,
    };

    return cached[capability] || 'Task completed successfully.';
}

